version: 2.1
orbs:
  node: circleci/node@5.2.0
  cypress: cypress-io/cypress@2.0.0
executors:
  node:
    docker:
      - image: 'cypress/base:20.12.2'
jobs:
  build-and-test:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint

workflows:
  build-and-test:
    jobs:
      - build-and-test
  cypress:
    jobs:
      - cypress/install:
          executor: node
          yarn: true

      - cypress/run:
          executor: node
          name: cypress-download-all
          requires:
            - cypress/install
          yarn: true
          start: yarn dev
          command-prefix: 'HAPPO_PROJECT=download-all HAPPO_DOWNLOAD_ALL=true yarn happo-e2e -- -- yarn'

      - cypress/run:
          executor: node
          name: cypress-local-snapshots
          requires:
            - cypress/install
          yarn: true
          start: yarn dev
          command-prefix: 'CYPRESS_HAPPO_USE_LOCAL_SNAPSHOTS=true HAPPO_PROJECT=local-snapshots yarn happo-e2e -- -- yarn'

      - cypress/run:
          executor: node
          name: cypress-allow-failures
          requires:
            - cypress/install
          yarn: true
          start: yarn dev
          command-prefix: |
            flip_exit_code() { ( "$@" ) && exit 1 || exit 0; }; CYPRESS_INTRODUCE_FAILING_ASSERTION=true HAPPO_PROJECT=allow-failures flip_exit_code yarn happo-e2e -- --allow-failures -- yarn

      - cypress/run:
          executor: node
          name: cypress-parallel
          requires:
            - cypress/install
          yarn: true
          start: yarn dev
          parallel: true
          parallelism: 2
          record: true
          command-prefix: 'HAPPO_PROJECT=parallel HAPPO_NONCE=${CIRCLE_WORKFLOW_ID} yarn happo-e2e -- -- yarn'
          post-steps:
            - run: 'HAPPO_PROJECT=parallel HAPPO_NONCE=${CIRCLE_WORKFLOW_ID} yarn happo-e2e -- finalize'

      - cypress/run:
          executor: node
          name: cypress-parallel-allow-failures
          requires:
            - cypress/install
          yarn: true
          start: yarn dev
          parallel: true
          parallelism: 2
          record: true
          ci-build-id: 'parallel-allow-failures-${CIRCLE_SHA1}'
          command-prefix: |
            flip_exit_code() { ( "$@" ) && exit 1 || exit 0; }; CYPRESS_INTRODUCE_FAILING_ASSERTION=true HAPPO_PROJECT=parallel-allow-failures HAPPO_NONCE=B_${CIRCLE_WORKFLOW_ID} flip_exit_code yarn happo-e2e -- --allow-failures -- yarn
          post-steps:
            - run: 'HAPPO_PROJECT=parallel-allow-failures HAPPO_NONCE=B_${CIRCLE_WORKFLOW_ID} yarn happo-e2e -- finalize'
