name: Automerge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    uses: happo/happo-view/.github/workflows/automerge.yml@main
    permissions:
      pull-requests: write
      contents: write
